package ca.bc.gov.educ.api.gradstudent.model.dc;

/**
 * The enum Event type.
 */
public enum EventType {
  VALIDATE_SDC_STUDENT,
  PROCESS_PEN_MATCH,
  FETCH_GRAD_STATUS,
  PROCESS_GRAD_STATUS_RESULT,
  PROCESS_PEN_MATCH_RESULTS,
  READ_FROM_TOPIC,
  INITIATED,
  MARK_SAGA_COMPLETE,
  GET_PAGINATED_SCHOOLS,
  WRITE_ENROLLED_PROGRAMS,
  CALCULATE_ADDITIONAL_STUDENT_ATTRIBUTES,
  GET_GRAD_STUDENT_RECORD,
  GET_STUDENT,
  GET_COURSE_FROM_EXTERNAL_ID,
  PROCESS_STUDENT_DEM_DATA,
  PROCESS_STUDENT_COURSE_DATA,
  UPDATE_SCHOOL_OF_RECORD
}
