package ca.bc.gov.educ.api.gradstudent.constant;

/**
 * The enum Event outcome.
 */
public enum EventOutcome {
  /**
   * Student updated event outcome.
   */
  GRAD_STATUS_UPDATED,
  DEM_STUDENT_PROCESSED_IN_GRAD_STUDENT_API,
  ASSESSMENT_STUDENT_UPDATED,
  SCHOOL_OF_RECORD_UPDATED,
  MERGE_CREATED,
  MERGE_DELETED,
  STUDENT_FOUND,
  STUDENT_NOT_FOUND,
  STUDENTS_FOUND,
  STUDENTS_NOT_FOUND,
  STUDENT_CREATED,
  STUDENT_UPDATED,
  STUDENT_ALREADY_EXIST,
  STUDENT_HISTORY_FOUND,
  STUDENT_HISTORY_NOT_FOUND,
  STUDENT_HISTORY_CREATED,
  STUDENT_HISTORY_ALREADY_EXIST,
  GRAD_STUDENT_CITIZENSHIP_UPDATED,
  VALIDATION_SUCCESS_NO_ERROR_WARNING,
  VALIDATION_SUCCESS_WITH_ERROR,
  PEN_MATCH_PROCESSED,
  GRAD_STATUS_FETCHED,
  GRAD_STATUS_RESULTS_PROCESSED,
  PEN_MATCH_RESULTS_PROCESSED,
  READ_FROM_TOPIC_SUCCESS,
  INITIATE_SUCCESS,
  SAGA_COMPLETED,
  ENROLLED_PROGRAMS_WRITTEN,
  ADDITIONAL_STUDENT_ATTRIBUTES_CALCULATED,
  COURSE_STUDENT_PROCESSED_IN_GRAD_STUDENT_API,
  GRAD_STUDENT_ADOPTED,
  STUDENT_COURSES_UPDATED;

  public static boolean isValid(String value) {
    if (value == null) {
      return false;
    }
    try {
      EventOutcome.valueOf(value);
      return true;
    } catch (IllegalArgumentException e) {
      return false;
    }
  }

}
