package ca.bc.gov.educ.api.gradstudent.constant;

/**
 * The enum Event type.
 */
public enum EventType {
  GRAD_STUDENT_GRADUATED,
  GRAD_STUDENT_UNDO_COMPLETION,
  GRAD_STUDENT_UPDATED,
  ASSESSMENT_STUDENT_UPDATE,
  UPDATE_SCHOOL_OF_RECORD,
  CREATE_MERGE,
  DELETE_MERGE,
  GET_STUDENT,
  GET_STUDENTS,
  CREATE_STUDENT,
  UPDATE_STUDENT,
  GET_STUDENT_HISTORY,
  GET_MERGES_IN_DATE_RANGE,
  CREATE_STUDENT_HISTORY,
  STUDENT_EVENT_OUTBOX_PROCESSED,
  GET_PAGINATED_STUDENT_BY_CRITERIA,
  UPDATE_GRAD_STUDENT_CITIZENSHIP,
  VALIDATE_SDC_STUDENT,
  PROCESS_PEN_MATCH,
  FETCH_GRAD_STATUS,
  PROCESS_GRAD_STATUS_RESULT,
  PROCESS_PEN_MATCH_RESULTS,
  READ_FROM_TOPIC,
  INITIATED,
  MARK_SAGA_COMPLETE,
  GET_PAGINATED_SCHOOLS,
  WRITE_ENROLLED_PROGRAMS,
  CALCULATE_ADDITIONAL_STUDENT_ATTRIBUTES,
  GET_GRAD_STUDENT_RECORD,
  GET_GRAD_STUDENT_COURSE_RECORDS,
  GET_COURSE_FROM_EXTERNAL_ID,
  PROCESS_STUDENT_DEM_DATA,
  PROCESS_STUDENT_COURSE_DATA,
  ADOPT_GRAD_STUDENT,
  GET_STUDENT_COURSES,
  UPDATE_STUDENT_COURSES;

  public static boolean isValid(String value) {
    if (value == null) {
      return false;
    }
    try {
      EventType.valueOf(value);
      return true;
    } catch (IllegalArgumentException e) {
      return false;
    }
  }
}
