package ca.bc.gov.educ.api.gradstudent.constant;

/**
 * The enum Event type.
 */
public enum EventType {
  GRAD_STUDENT_GRADUATED,
  GRAD_STUDENT_UNDO_COMPLETION,
  GRAD_STUDENT_UPDATED,
  ASSESSMENT_STUDENT_UPDATE,
  UPDATE_SCHOOL_OF_RECORD,
  CREATE_MERGE,
  DELETE_MERGE,
  GET_STUDENT,
  GET_STUDENTS,
  CREATE_STUDENT,
  UPDATE_STUDENT,
  GET_STUDENT_HISTORY,
  CREATE_STUDENT_HISTORY,
  STUDENT_EVENT_OUTBOX_PROCESSED,
  GET_PAGINATED_STUDENT_BY_CRITERIA
}
