package ca.bc.gov.educ.api.gradstudent.constant;

/**
 * The enum Event outcome.
 */
public enum EventOutcome {
  /**
   * Student updated event outcome.
   */
  GRAD_STATUS_UPDATED,
  DEM_STUDENT_PROCESSED_IN_GRAD_STUDENT_API,
  ASSESSMENT_STUDENT_UPDATED,
  SCHOOL_OF_RECORD_UPDATED,
  MERGE_CREATED,
  MERGE_DELETED,
  STUDENT_FOUND,
  STUDENT_NOT_FOUND,
  STUDENTS_FOUND,
  STUDENTS_NOT_FOUND,
  STUDENT_CREATED,
  STUDENT_UPDATED,
  STUDENT_ALREADY_EXIST,
  STUDENT_HISTORY_FOUND,
  STUDENT_HISTORY_NOT_FOUND,
  STUDENT_HISTORY_CREATED,
  STUDENT_HISTORY_ALREADY_EXIST
}
