package ca.bc.gov.educ.api.gradstudent.constant;

/**
 * The enum Event outcome.
 */
public enum EventOutcome {
  /**
   * Student updated event outcome.
   */
  GRAD_STATUS_UPDATED,
  VALIDATION_SUCCESS_NO_ERROR_WARNING,
  VALIDATION_SUCCESS_WITH_ERROR,
  PEN_MATCH_PROCESSED,
  GRAD_STATUS_FETCHED,
  GRAD_STATUS_RESULTS_PROCESSED,
  PEN_MATCH_RESULTS_PROCESSED,
  READ_FROM_TOPIC_SUCCESS,
  INITIATE_SUCCESS,
  SAGA_COMPLETED,
  ENROLLED_PROGRAMS_WRITTEN,
  ADDITIONAL_STUDENT_ATTRIBUTES_CALCULATED,
  STUDENTS_ARCHIVED,
  BATCH_API_NOTIFIED
}
