package ca.bc.gov.educ.api.gradstudent.constant;

/**
 * The enum Event type.
 */
public enum EventType {
  GRAD_STUDENT_GRADUATED,
  GRAD_STUDENT_UNDO_COMPLETION,
  GRAD_STUDENT_UPDATED,
  VALIDATE_SDC_STUDENT,
  PROCESS_PEN_MATCH,
  FETCH_GRAD_STATUS,
  PROCESS_GRAD_STATUS_RESULT,
  PROCESS_PEN_MATCH_RESULTS,
  READ_FROM_TOPIC,
  INITIATED,
  MARK_SAGA_COMPLETE,
  GET_PAGINATED_SCHOOLS,
  WRITE_ENROLLED_PROGRAMS,
  CALCULATE_ADDITIONAL_STUDENT_ATTRIBUTES,
  ARCHIVE_STUDENTS,
  NOTIFY_ARCHIVE_STUDENT_BATCH_COMPLETED,
  ARCHIVE_STUDENTS_REQUEST
}
