package ca.bc.gov.educ.api.gradstudent.constant;

/**
 * The enum Topics.
 */
public enum Topics {
  /**
   * GradStatus events topic.
   */
  GRAD_STATUS_EVENT_TOPIC,
  GRAD_STUDENT_API_FETCH_GRAD_STATUS_TOPIC,
  GRAD_STUDENT_API_FETCH_GRAD_STATUS_TOPIC_V2,
  GRAD_STUDENT_API_FETCH_GRAD_STUDENT_TOPIC,
  GRAD_STUDENT_API_FETCH_GRAD_STUDENT_COURSES_TOPIC,
  GRAD_STUDENT_API_TOPIC,
  STUDENT_EVENTS_TOPIC,
  COREG_API_TOPIC,
  STUDENT_ASSESSMENT_EVENTS_TOPIC,
  PEN_SERVICES_EVENTS_TOPIC
}
