CREATE TABLE HISTORIC_STUDENT_ACTIVITY
    NOLOGGING
    PARALLEL 8
AS
SELECT
    SYS_GUID() AS HISTORIC_STUDENT_ACTIVITY_ID,
    sld.STUDENT_ID AS GRADUATION_STUDENT_RECORD_ID,
    sa.ACTV_DATE AS "ACTIVITY_DATE",
    TRIM(sa.ACTV_TYPE) AS "TYPE",
    TRIM(sa.ACTV_PROGRAM) AS PROGRAM,
    TRIM(sa.ACTV_USERID) AS USER_ID,
    TRIM(sa.ACTV_BATCH) AS BATCH,
    TRIM(sa.ACTV_SEQN) AS SEQ_NO,
    'STUDENT_ACTIVITY_MIGRATION' AS CREATE_USER,
    SYSDATE AS CREATE_DATE,
    'STUDENT_ACTIVITY_MIGRATION' AS UPDATE_USER,
    SYSDATE AS UPDATE_DATE
FROM STUDENT_ACTIVITY sa
         JOIN STUDENT_LINK sld ON sld.PEN = TRIM(sa.STUD_NO);