ALTER TABLE "STUDENT_COURSE_EXAM" ADD "WROTE_FLAG" VARCHAR2(1);
ALTER TABLE "STUDENT_COURSE_EXAM" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "STUDENT_COURSE_EXAM" MODIFY "UPDATE_USER" VARCHAR2(100);
