-- API_GRAD_STUDENT.STUDENT_GRADE_CODE definition

CREATE TABLE "STUDENT_GRADE_CODE"
(	"STUDENT_GRADE_CODE" VARCHAR2(2) NOT NULL,
     "LABEL" VARCHAR2(30) NOT NULL,
     "DESCRIPTION" VARCHAR2(125) NOT NULL,
     "DISPLAY_ORDER" NUMBER NOT NULL,
     "EFFECTIVE_DATE" DATE NOT NULL,
     "EXPIRY_DATE" DATE,
     "EXPECTED" VARCHAR2(1) NOT NULL,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL,
     "CREATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL,
     "UPDATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL,
     CONSTRAINT "STUDENT_GRADE_CODE_PK" PRIMARY KEY ("STUDENT_GRADE_CODE")
         USING INDEX TABLESPACE "API_GRAD_IDX"
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;
