ALTER TABLE API_GRAD_STUDENT.GRADUATION_STUDENT_RECORD MODIFY CREATE_USER VARCHAR2(50) DEFAULT USER ;
ALTER TABLE API_GRAD_STUDENT.GRADUATION_STUDENT_RECORD MODIFY UPDATE_USER VARCHAR2(50) DEFAULT USER ;
ALTER TABLE API_GRAD_STUDENT.GRADUATION_STUDENT_RECORD_HISTORY MODIFY CREATE_USER VARCHAR2(50) DEFAULT USER ;
ALTER TABLE API_GRAD_STUDENT.GRADUATION_STUDENT_RECORD_HISTORY MODIFY UPDATE_USER VARCHAR2(50) DEFAULT USER ;