ALTER TABLE EDW_GRADUATION_SNAPSHOT DROP COLUMN NOT_GRAD_REASON_1;
ALTER TABLE EDW_GRADUATION_SNAPSHOT DROP COLUMN NOT_GRAD_REASON_2;
ALTER TABLE EDW_GRADUATION_SNAPSHOT DROP COLUMN NOT_GRAD_REASON_3;
ALTER TABLE EDW_GRADUATION_SNAPSHOT DROP COLUMN NOT_GRAD_REASON_4;
ALTER TABLE EDW_GRADUATION_SNAPSHOT DROP COLUMN NOT_GRAD_REASON_5;
ALTER TABLE EDW_GRADUATION_SNAPSHOT DROP COLUMN NOT_GRAD_REASON_6;
ALTER TABLE EDW_GRADUATION_SNAPSHOT DROP COLUMN NOT_GRAD_REASON_7;
ALTER TABLE EDW_GRADUATION_SNAPSHOT DROP COLUMN NOT_GRAD_REASON_8;
ALTER TABLE EDW_GRADUATION_SNAPSHOT DROP COLUMN NOT_GRAD_REASON_9;
ALTER TABLE EDW_GRADUATION_SNAPSHOT DROP COLUMN NOT_GRAD_REASON_10;
ALTER TABLE EDW_GRADUATION_SNAPSHOT DROP COLUMN NOT_GRAD_REASON_11;
ALTER TABLE EDW_GRADUATION_SNAPSHOT DROP COLUMN NOT_GRAD_REASON_12;


