-- API_GRAD_STUDENT.GRADUATION_STUDENT_RECORD_HISTORY definition

CREATE TABLE "GRADUATION_STUDENT_RECORD_HISTORY"
   (	"GRADUATION_STUDENT_RECORD_HISTORY_ID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE,
	"GRADUATION_STUDENT_RECORD_ID" RAW(16) NOT NULL ENABLE,
	"GRADUATION_PROGRAM_CODE" VARCHAR2(8) NOT NULL ENABLE,
	"GPA" NUMBER,
	"STUDENT_STATUS_CODE" VARCHAR2(1),
	"HONOURS_STANDING" VARCHAR2(1),
	"PROGRAM_COMPLETION_DATE" DATE,
	"RECALCULATE_GRAD_STATUS" VARCHAR2(1),
	"SCHOOL_OF_RECORD" VARCHAR2(9),
	"STUDENT_GRADE" VARCHAR2(3),
	"STUDENT_GRAD_DATA" CLOB,
	"SCHOOL_AT_GRADUATION" VARCHAR2(9),
	"CREATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
	"CREATE_DATE" DATE DEFAULT systimestamp NOT NULL ENABLE,
	"UPDATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
	"UPDATE_DATE" DATE DEFAULT systimestamp NOT NULL ENABLE,
	"HISTORY_ACTIVITY_CODE" VARCHAR2(15) NOT NULL ENABLE,
	 CONSTRAINT "GRADUATION_STUDENT_RECORD_HISTORY_PK" PRIMARY KEY ("GRADUATION_STUDENT_RECORD_HISTORY_ID")
  USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE,
	 CONSTRAINT "GRAD_STUD_REC_HSTRY_HSTRY_ACTVTYCD_FK" FOREIGN KEY ("HISTORY_ACTIVITY_CODE")
	  REFERENCES "HISTORY_ACTIVITY_CODE" ("HISTORY_ACTIVITY_CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY
 LOB ("STUDENT_GRAD_DATA") STORE AS SECUREFILE (
  TABLESPACE "API_GRAD_BLOB_DATA" ENABLE STORAGE IN ROW
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES );
