ALTER TABLE EDW_GRADUATION_SNAPSHOT ADD SCHOOL_OF_RECORD_ID RAW(16);

ALTER TABLE GRADUATION_STUDENT_RECORD ADD SCHOOL_OF_RECORD_ID RAW(16);
ALTER TABLE GRADUATION_STUDENT_RECORD ADD SCHOOL_AT_GRADUATION_ID RAW(16);

ALTER TABLE GRADUATION_STUDENT_RECORD_HISTORY ADD SCHOOL_OF_RECORD_ID RAW(16);
ALTER TABLE GRADUATION_STUDENT_RECORD_HISTORY ADD SCHOOL_AT_GRADUATION_ID RAW(16);
