BEGIN
EXECUTE IMMEDIATE 'DROP SYNONYM API_GRAD_STUDENT.STUDENT_MASTER';
EXCEPTION
    WHEN OTHERS THEN
      -- ORA-01434: private synonym does not exist
      IF SQLCODE != -1434 THEN
        RAISE;
END IF;
END;