CREATE TABLE "HISTORIC_STUDENT_ACTIVITY"
(	"HISTORIC_STUDENT_ACTIVITY_ID" RAW(16) DEFAULT SYS_GUID(),
     "GRADUATION_STUDENT_RECORD_ID" RAW(16) NOT NULL ENABLE,
     "ACTIVITY_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "TYPE" VARCHAR2(3),
     "PROGRAM" VARCHAR2(12),
     "USER_ID" VARCHAR2(12),
     "BATCH" VARCHAR2(3),
     "SEQ_NO" VARCHAR2(4),
     "CREATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "UPDATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     CONSTRAINT "HISTORIC_STUDENT_ACTIVITY_ID_PK" PRIMARY KEY ("HISTORIC_STUDENT_ACTIVITY_ID")
         USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE
) SEGMENT CREATION IMMEDIATE
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY;

CREATE INDEX IDX_STUDENT_ACTIVITY_GRADUATION_STUDENT_RECORD_ID
    ON HISTORIC_STUDENT_ACTIVITY ("GRADUATION_STUDENT_RECORD_ID")
    TABLESPACE "API_GRAD_IDX";