ALTER TABLE EDW_GRADUATION_SNAPSHOT DROP COLUMN PRINT_FRENCH_DOG;
ALTER TABLE EDW_GRADUATION_SNAPSHOT DROP COLUMN PRINT_FRANCOPHONE;
ALTER TABLE EDW_GRADUATION_SNAPSHOT ADD "SCHOOL_OF_RECORD" VARCHAR2(9 BYTE);

