INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE)
VALUES ('USEREDITTVRFLAG','User Modify Recalculate Projected Grad ','Recalculate Projected Grad flag updated by User',200,TIMESTAMP'2023-11-27 00:00:00.0',NULL);


INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE)
VALUES ('USEREDITALGFLAG','User Modify Recalculate Grad Status ','Recalculate Grad Status flag updated by User',260,TIMESTAMP'2023-11-27 00:00:00.0',NULL);
