INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) 
VALUES ('GDCUPATE','GDC Update','Record updated by GDC File',70,TIMESTAMP'2021-09-29 13:27:12.0',NULL);

INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE)
VALUES ('GDCADD','GDC Add','Record added by GDC File',70,TIMESTAMP'2021-09-29 13:27:12.0',NULL);