ALTER TABLE "STUDENT_COURSE_EXAM" ADD "STUDENT_COURSE_ID" RAW(16) NOT NULL ENABLE;
ALTER TABLE "STUDENT_COURSE_EXAM" ADD "WROTE_FLAG" VARCHAR2(1);
ALTER TABLE "STUDENT_COURSE_EXAM" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "STUDENT_COURSE_EXAM" MODIFY "UPDATE_USER" VARCHAR2(100);
ALTER TABLE "STUDENT_COURSE_EXAM" ADD CONSTRAINT "STUDENT_COURSE_FK"
FOREIGN KEY ("STUDENT_COURSE_ID")
REFERENCES "STUDENT_COURSE" ("STUDENT_COURSE_ID") ENABLE;
