
CREATE TABLE "STUDENT_RECORD_NOTE"
(	"STUDENT_RECORD_NOTE_ID" RAW(16) DEFAULT SYS_GUID(),
     "GRADUTION_STUDENT_RECORD_ID" RAW(16) NOT NULL ENABLE,
     "RECORD_NOTE" VARCHAR2(255 BYTE) NOT NULL ENABLE,
     "CREATE_USER" VARCHAR2(32 BYTE) DEFAULT USER NOT NULL ENABLE,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "UPDATE_USER" VARCHAR2(32 BYTE) DEFAULT USER NOT NULL ENABLE,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     CONSTRAINT "STUDENT_RECORD_NOTE_PK" PRIMARY KEY ("STUDENT_RECORD_NOTE_ID")
         USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE,
     CONSTRAINT "STUD_REC_NT_GRDSTUD_REC_FK" FOREIGN KEY ("GRADUTION_STUDENT_RECORD_ID")
         REFERENCES "GRADUATION_STUDENT_RECORD" ("GRADUATION_STUDENT_RECORD_ID") ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;

