ALTER TABLE GRADUATION_STUDENT_RECORD
    ADD (
    PEN               VARCHAR2(9 CHAR),
    LEGAL_FIRST_NAME  VARCHAR2(255 CHAR),
    LEGAL_LAST_NAME   VARCHAR2(255 CHAR),
    LEGL_MIDDLE_NAMES VARCHAR2(255 CHAR),
    DOB               DATE,
    GENDER_CODE       VARCHAR2(1 CHAR)
  );

CREATE INDEX IDX_GRAD_STUD_REC_PEN
    ON GRADUATION_STUDENT_RECORD (PEN);