CREATE INDEX IDX_GSR_ASSESS_COMP_CUR
    ON GRADUATION_STUDENT_RECORD (
        SCHOOL_OF_RECORD_ID,
        STUDENT_STATUS_CODE,
        LEGAL_LAST_NAME,
        LEGAL_FIRST_NAME,
        GRADUATION_STUDENT_RECORD_ID
    )
    TABLESPACE API_GRAD_IDX;
