INSERT INTO HISTORY_ACTIVITY_CODE
(HISTORY_ACTIVITY_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE)
VALUES('USERDISTPSIF', 'User Distribution Run PSI FTP', 'Record updated by User Requested Distribution Run for PSI Transcript Print FTP', 30, TIMESTAMP'2021-09-29 13:27:12.0',NULL);

UPDATE GRADUATION_STUDENT_RECORD_HISTORY
SET HISTORY_ACTIVITY_CODE='USERDISTPSIF'
WHERE HISTORY_ACTIVITY_CODE='USERDISTPISF';

UPDATE STUDENT_OPTIONAL_PROGRAM_HISTORY
SET HISTORY_ACTIVITY_CODE='USERDISTPSIF'
WHERE HISTORY_ACTIVITY_CODE='USERDISTPISF';

DELETE FROM HISTORY_ACTIVITY_CODE
WHERE HISTORY_ACTIVITY_CODE = 'USERDISTPISF';