ALTER TABLE STUDENT_OPTIONAL_PROGRAM
    ADD CONSTRAINT STUDENT_OPTIONAL_PROGRAM_UK UNIQUE (
        GRADUATION_STUDENT_RECORD_ID
        ,OPTIONAL_PROGRAM_ID
    )
USING INDEX API_GRAD_STUDENT.SYS_AI_c2ky4yrnrs1ca
ENABLE;





