INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE)
VALUES ('USERSTUDARC','User Student Archive','Record updated by User Requested Archive Process',250,TIMESTAMP'2023-05-24 00:00:00.0',NULL);
