INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) VALUES ('NONGRADYERUN','Non-Grad Year End Distribution Run','Record updated by Non-Grad Year End Distribution Run',230,TIMESTAMP'2022-12-13 13:27:12.0',NULL);

