INSERT INTO HISTORY_ACTIVITY_CODE
(HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE)
VALUES
    ('INSTITUTEALERT','Institute Alert','Alerts received from Institute when either school or district data has changed',270,
     TIMESTAMP'2024-06-21 00:00:00.0',NULL);


INSERT INTO HISTORY_ACTIVITY_CODE
(HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE)
VALUES
    ('PENALERT','PEN Alert','Alerts received from PEN when student demographic data has changed',280,
     TIMESTAMP'2024-06-21 00:00:00.0',NULL);


INSERT INTO HISTORY_ACTIVITY_CODE
(HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE)
VALUES
    ('COREGALERT','Coreg Alert','Alerts received from Coreg when course data has changed',290,
     TIMESTAMP'2024-06-21 00:00:00.0',NULL);
