CREATE OR REPLACE VIEW REPORT_GRAD_DISTRICT_YE_VW AS
  SELECT DISTINCT
    SUBSTR(A1.SCHOOL_OF_RECORD, 0, 3) MINCODE
FROM
    GRADUATION_STUDENT_RECORD A1
WHERE
        A1.PROGRAM_COMPLETION_DATE is null
  AND A1.STUDENT_STATUS_CODE = 'CUR'
  AND (A1.STUDENT_GRADE ='AD' or A1.STUDENT_GRADE='12')
GROUP BY SUBSTR(A1.SCHOOL_OF_RECORD, 0, 3)
ORDER BY 1 DESC;

