CREATE TABLE GRAD_STUDENT_SAGA
(
    SAGA_ID     RAW(16)              NOT NULL,
    BATCH_ID  RAW(16),
    SAGA_NAME   VARCHAR2(50)         NOT NULL,
    SAGA_STATE  VARCHAR2(100)        NOT NULL,
    PAYLOAD     BLOB                 NOT NULL,
    STATUS      VARCHAR2(20)         NOT NULL,
    CREATE_USER VARCHAR2(50)         NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER VARCHAR2(50)         NOT NULL,
    UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    RETRY_COUNT NUMBER,
    CONSTRAINT GRAD_STUDENT_SAGA_PK PRIMARY KEY (SAGA_ID)
)
    LOB (PAYLOAD) STORE AS PAYLOAD (TABLESPACE API_GRAD_BLOB_DATA);

CREATE INDEX GRAD_STUDENT_SAGA_STATUS_IDX ON GRAD_STUDENT_SAGA (STATUS);
CREATE INDEX GRAD_STUDENT_SAGA_STUDENT_ID_IDX ON GRAD_STUDENT_SAGA (BATCH_ID);

CREATE TABLE GRAD_STUDENT_SAGA_EVENT_STATES
(
    SAGA_EVENT_ID       RAW(16)              NOT NULL,
    SAGA_ID             RAW(16)              NOT NULL,
    SAGA_EVENT_STATE    VARCHAR2(100)        NOT NULL,
    SAGA_EVENT_OUTCOME  VARCHAR2(100)        NOT NULL,
    SAGA_STEP_NUMBER    NUMBER(4)            NOT NULL,
    SAGA_EVENT_RESPONSE BLOB                 NOT NULL,
    CREATE_USER         VARCHAR2(50)         NOT NULL,
    CREATE_DATE         DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER         VARCHAR2(50)         NOT NULL,
    UPDATE_DATE         DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT GRAD_STUDENT_SAGA_EVENT_STATES_PK PRIMARY KEY (SAGA_EVENT_ID)
)
    LOB (SAGA_EVENT_RESPONSE) STORE AS SAGA_EVENT_RESPONSE (TABLESPACE API_GRAD_BLOB_DATA);

ALTER TABLE GRAD_STUDENT_SAGA_EVENT_STATES
    ADD CONSTRAINT GRAD_STUDENT_SAGA_EVENT_STATES_SAGA_ID_FK FOREIGN KEY (SAGA_ID) REFERENCES GRAD_STUDENT_SAGA (SAGA_ID);
