INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) VALUES ('USERUNDOCMPL','User Undo Completion','User Undo Student Program Completion',130,TIMESTAMP'2021-09-29 13:27:12.0',NULL);

UPDATE GRADUATION_STUDENT_RECORD_HISTORY SET HISTORY_ACTIVITY_CODE = 'USERUNDOCMPL'
WHERE HISTORY_ACTIVITY_CODE = 'USERUNGRAD';

DELETE FROM HISTORY_ACTIVITY_CODE
WHERE HISTORY_ACTIVITY_CODE = 'USERUNGRAD';
