INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) VALUES ('MONTHLYDIST','Monthly Distribution Run','Record updated by Monthly Distribution Run',110,TIMESTAMP'2021-09-29 13:27:12.0',NULL);
INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) VALUES ('YEARENDDIST','Year End Distribution Run','Record updated by Year End Distribution Run',140,TIMESTAMP'2021-09-29 13:27:12.0',NULL);
INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) VALUES ('USERDIST','User Distribution Run','Record updated by User Requested Distribution Run',150,TIMESTAMP'2021-09-29 13:27:12.0',NULL);

UPDATE GRADUATION_STUDENT_RECORD_HISTORY SET HISTORY_ACTIVITY_CODE = 'DISTRIBUTION'
WHERE HISTORY_ACTIVITY_CODE = 'MONTHLYDIST';

DELETE FROM HISTORY_ACTIVITY_CODE
WHERE HISTORY_ACTIVITY_CODE = 'DISTRIBUTION';
