INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) 
VALUES ('ASSESSUPD','Assessment Update','Student assessment record was updated',70,TIMESTAMP'2021-09-29 13:27:12.0',NULL);
