
CREATE TABLE"STUDENT_CAREER_PROGRAM"
(	"STUDENT_CAREER_PROGRAM_ID" RAW(16) DEFAULT SYS_GUID(),
     "GRADUTION_STUDENT_RECORD_ID" RAW(16) NOT NULL ENABLE,
     "CAREER_PROGRAM_CODE" VARCHAR2(3 BYTE) NOT NULL ENABLE,
     "CREATE_USER" VARCHAR2(32 BYTE) DEFAULT USER NOT NULL ENABLE,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "UPDATE_USER" VARCHAR2(32 BYTE) DEFAULT USER NOT NULL ENABLE,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     CONSTRAINT "STUDENT_CAREER_PROGRAM_PK" PRIMARY KEY ("STUDENT_CAREER_PROGRAM_ID")
         USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE,
     CONSTRAINT "STUD_CRPGM_GRDSTUD_REC_FK" FOREIGN KEY ("GRADUTION_STUDENT_RECORD_ID")
         REFERENCES "GRADUATION_STUDENT_RECORD" ("GRADUATION_STUDENT_RECORD_ID") ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA" NO INMEMORY ;
