INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) VALUES ('USERCOURSEADD','User Add Student Course','Student course record added by User',300,TIMESTAMP'2025-05-09 00:00:00.0',NULL);

INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) VALUES ('USERCOURSEMOD','User Modify Student Course','Student course record modified by User',310,TIMESTAMP'2025-05-09 00:00:00.0',NULL);

INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) VALUES ('USERCOURSEDEL','User Deleted Student Course','Student course record deleted by User',320,TIMESTAMP'2025-05-09 00:00:00.0',NULL);
