ALTER TABLE "STUDENT_COURSE" DROP CONSTRAINT "STUDENT_COURSE_EXAM_FK";
ALTER TABLE "STUDENT_COURSE" DROP COLUMN "STUDENT_COURSE_EXAM_ID";
ALTER TABLE "STUDENT_COURSE" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "STUDENT_COURSE" MODIFY "UPDATE_USER" VARCHAR2(100);
ALTER TABLE "STUDENT_COURSE_HISTORY" DROP COLUMN "STUDENT_COURSE_EXAM_ID";

