-- API_GRAD_STUDENT.STUDENT_CITIZENSHIP_CODE definition

CREATE TABLE "STUDENT_CITIZENSHIP_CODE"
   (	"STUDENT_CITIZENSHIP_CODE" VARCHAR2(1) NOT NULL ENABLE,
	"LABEL" VARCHAR2(30) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(100) NOT NULL ENABLE,
	"DISPLAY_ORDER" NUMBER NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE, 
	"CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"CREATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE, 
	"UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE, 
	 CONSTRAINT "STUDENT_CITIZENSHIP_CODE_PK" PRIMARY KEY ("STUDENT_CITIZENSHIP_CODE")
  USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;
