GRANT SELECT ON GRADUATION_STUDENT_RECORD TO GRAD_READONLY;
GRANT SELECT ON GRADUATION_STUDENT_RECORD_HISTORY TO GRAD_READONLY;
GRANT SELECT ON HISTORY_ACTIVITY_CODE TO GRAD_READONLY;
GRANT SELECT ON STUDENT_CAREER_PROGRAM TO GRAD_READONLY;
GRANT SELECT ON STUDENT_OPTIONAL_PROGRAM TO GRAD_READONLY;
GRANT SELECT ON STUDENT_OPTIONAL_PROGRAM_HISTORY TO GRAD_READONLY;
GRANT SELECT ON STUDENT_RECORD_NOTE TO GRAD_READONLY;
GRANT SELECT ON STUDENT_CITIZENSHIP_CODE TO GRAD_READONLY;
GRANT SELECT ON STUDENT_STATUS_CODE TO GRAD_READONLY;

