INSERT INTO STUDENT_OPTIONAL_PROGRAM
SELECT
    SYS_GUID() as STUDENT_OPTIONAL_PROGRAM_ID
    ,'C71BA15E1CB8CCCEE05398E9228E1B71' as OPTIONAL_PROGRAM_ID -- FI	2018-EN
    ,STUDENT_GUID as GRADUATION_STUDENT_RECORD_ID
    ,NULL as COMPLETION_DATE
    ,NULL as PROGRAM_NOTE
    ,'DATA_CONV' as CREATE_USER
    ,SYSDATE as CREATE_DATE
    ,'Batch Process' as UPDATE_USER
    ,SYSDATE as UPDATE_DATE
FROM
    STUDENT_GUID_PEN_XREF
WHERE
    STUDENT_PEN IN (
        '144570215',
        '143910560',
        '131814154',
        '132821091'
    )

;

INSERT INTO STUDENT_OPTIONAL_PROGRAM
SELECT
    SYS_GUID() as STUDENT_OPTIONAL_PROGRAM_ID
     ,'EF1CB159B2CED581E05398E9228E36D9' as OPTIONAL_PROGRAM_ID -- FI	2023-EN
     ,STUDENT_GUID as GRADUATION_STUDENT_RECORD_ID
     ,NULL as COMPLETION_DATE
     ,NULL as PROGRAM_NOTE
     ,'DATA_CONV' as CREATE_USER
     ,SYSDATE as CREATE_DATE
     ,'Batch Process' as UPDATE_USER
     ,SYSDATE as UPDATE_DATE
FROM
    STUDENT_GUID_PEN_XREF
WHERE
        STUDENT_PEN IN (
                        '144570215',
                        '143910560',
                        '131814154',
                        '132821091'
        )

;

UPDATE GRADUATION_STUDENT_RECORD
SET
    RECALCULATE_GRAD_STATUS = 'Y'
    ,RECALCULATE_PROJECTED_GRAD = 'Y'
    ,UPDATE_USER = 'Batch Process'
    ,UPDATE_DATE = SYSDATE
WHERE
    GRADUATION_STUDENT_RECORD_ID IN (
        SELECT STUDENT_GUID FROM STUDENT_GUID_PEN_XREF WHERE
                STUDENT_PEN IN (
                                '144570215',
                                '143910560',
                                '131814154',
                                '132821091'
                )
    )

;

INSERT INTO STUDENT_OPTIONAL_PROGRAM_HISTORY
SELECT
    SYS_GUID() as STUDENT_OPTIONAL_PROGRAM_HISTORY_ID
    ,'DATACONVERT' HISTORY_ACTIVITY_CODE
    ,STUDENT_OPTIONAL_PROGRAM_ID
    ,OPTIONAL_PROGRAM_ID
    ,GRADUATION_STUDENT_RECORD_ID
    ,COMPLETION_DATE
    ,CREATE_USER
    ,CREATE_DATE
    ,UPDATE_USER
    ,UPDATE_DATE
FROM
    STUDENT_OPTIONAL_PROGRAM
WHERE
    OPTIONAL_PROGRAM_ID IN (
        'EF1CB159B2CED581E05398E9228E36D9',
        'C71BA15E1CB8CCCEE05398E9228E1B71'
    )
AND
   GRADUATION_STUDENT_RECORD_ID IN (
        SELECT STUDENT_GUID FROM STUDENT_GUID_PEN_XREF WHERE
                STUDENT_PEN IN (
                                '144570215',
                                '143910560',
                                '131814154',
                                '132821091'
                )
    )
;

COMMIT
;


