--GRAD2-1524, REVERT CHANGE IN 0.30, delete STUDENT_STATUS_CODE = 'HIS'
-- PART 1, DELETE records from child table if there is any
DELETE FROM GRADUATION_STUDENT_RECORD WHERE STUDENT_STATUS_CODE = 'HIS';

-- PART 2, DELETE STUDENT_STATUS_CODE = 'HIS' FROM STUDENT_STATUS_CODE table
DELETE FROM STUDENT_STATUS_CODE WHERE STUDENT_STATUS_CODE = 'HIS';