CREATE TABLE "GRADUATION_STUDENT_RECORD"
(	"GRADUATION_STUDENT_RECORD_ID" RAW(16) DEFAULT SYS_GUID(),
     "GRADUATION_PROGRAM_CODE" VARCHAR2(8 BYTE) NOT NULL ENABLE,
     "GPA" NUMBER,
     "STUDENT_STATUS_CODE" VARCHAR2(3 BYTE),
     "HONOURS_STANDING" VARCHAR2(1 BYTE),
     "PROGRAM_COMPLETION_DATE" DATE,
     "RECALCULATE_GRAD_STATUS" VARCHAR2(1 BYTE),
     "SCHOOL_OF_RECORD" VARCHAR2(9 BYTE),
     "STUDENT_GRADE" VARCHAR2(3 BYTE),
     "STUDENT_GRAD_DATA" CLOB,
     "SCHOOL_AT_GRADUATION" VARCHAR2(9 BYTE),
     "CREATE_USER" VARCHAR2(32 BYTE) DEFAULT USER NOT NULL ENABLE,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "UPDATE_USER" VARCHAR2(32 BYTE) DEFAULT USER NOT NULL ENABLE,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     CONSTRAINT "GRADUTION_STUDENT_RECORD_PK" PRIMARY KEY ("GRADUATION_STUDENT_RECORD_ID")
         USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE,
     CONSTRAINT "GRDSTUD_REC_STUD_STS_CD_FK" FOREIGN KEY ("STUDENT_STATUS_CODE")
         REFERENCES "STUDENT_STATUS_CODE" ("STUDENT_STATUS_CODE") ENABLE
) SEGMENT CREATION IMMEDIATE
    TABLESPACE "API_GRAD_DATA"   NO INMEMORY
    LOB ("STUDENT_GRAD_DATA") STORE AS SECUREFILE (
    TABLESPACE "API_GRAD_BLOB_DATA" ENABLE STORAGE IN ROW
    NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES) ;
