--Transaction Tables

ALTER TABLE "GRADUATION_STUDENT_RECORD" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "GRADUATION_STUDENT_RECORD" MODIFY "UPDATE_USER" VARCHAR2(100);

ALTER TABLE "GRADUATION_STUDENT_RECORD_HISTORY" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "GRADUATION_STUDENT_RECORD_HISTORY" MODIFY "UPDATE_USER" VARCHAR2(100);

ALTER TABLE "STUDENT_COURSE_EXAM_HISTORY" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "STUDENT_COURSE_EXAM_HISTORY" MODIFY "UPDATE_USER" VARCHAR2(100);

ALTER TABLE "STUDENT_COURSE_HISTORY" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "STUDENT_COURSE_HISTORY" MODIFY "UPDATE_USER" VARCHAR2(100);

ALTER TABLE "STUDENT_OPTIONAL_PROGRAM" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "STUDENT_OPTIONAL_PROGRAM" MODIFY "UPDATE_USER" VARCHAR2(100);

ALTER TABLE "STUDENT_OPTIONAL_PROGRAM_HISTORY" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "STUDENT_OPTIONAL_PROGRAM_HISTORY" MODIFY "UPDATE_USER" VARCHAR2(100);

ALTER TABLE "STUDENT_GUID_PEN_XREF" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "STUDENT_GUID_PEN_XREF" MODIFY "UPDATE_USER" VARCHAR2(100);

ALTER TABLE "STUDENT_RECORD_NOTE" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "STUDENT_RECORD_NOTE" MODIFY "UPDATE_USER" VARCHAR2(100);

ALTER TABLE "STUDENT_CAREER_PROGRAM" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "STUDENT_CAREER_PROGRAM" MODIFY "UPDATE_USER" VARCHAR2(100);

ALTER TABLE "STATUS_EVENT" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "STATUS_EVENT" MODIFY "UPDATE_USER" VARCHAR2(100);

-- Code Tables
ALTER TABLE "EQUIVALENT_OR_CHALLENGE_CODE" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "EQUIVALENT_OR_CHALLENGE_CODE" MODIFY "UPDATE_USER" VARCHAR2(100);

ALTER TABLE "EXAM_SPECIAL_CASE_CODE" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "EXAM_SPECIAL_CASE_CODE" MODIFY "UPDATE_USER" VARCHAR2(100);

ALTER TABLE "FINE_ARTS_APPLIED_SKILLS_CODE" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "FINE_ARTS_APPLIED_SKILLS_CODE" MODIFY "UPDATE_USER" VARCHAR2(100);

ALTER TABLE "HISTORY_ACTIVITY_CODE" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "HISTORY_ACTIVITY_CODE" MODIFY "UPDATE_USER" VARCHAR2(100);

ALTER TABLE "STUDENT_CITIZENSHIP_CODE" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "STUDENT_CITIZENSHIP_CODE" MODIFY "UPDATE_USER" VARCHAR2(100);

ALTER TABLE "STUDENT_STATUS_CODE" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "STUDENT_STATUS_CODE" MODIFY "UPDATE_USER" VARCHAR2(100);

ALTER TABLE "STUDENT_GRADE_CODE" MODIFY "CREATE_USER" VARCHAR2(100);
ALTER TABLE "STUDENT_GRADE_CODE" MODIFY "UPDATE_USER" VARCHAR2(100);
