INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) VALUES ('SUPPDIST','Supplemental Distribution Run','Record updated by Supplemental Distribution Run',210,TIMESTAMP'2022-12-13 13:27:12.0',NULL);
INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) VALUES ('NONGRADRUN','Non-Grad Distribution Run','Record updated by Non-Grad Distribution Run',220,TIMESTAMP'2022-12-13 13:27:12.0',NULL);

