
CREATE TABLE "STUDENT_RECORD_NOTE"
(	"STUDENT_RECORD_NOTE_ID" RAW(16) DEFAULT SYS_GUID(),
     "GRADUTION_STUDENT_RECORD_ID" RAW(16) NOT NULL ENABLE,
     "RECORD_NOTE" VARCHAR2(255 BYTE) NOT NULL ENABLE,
     "CREATE_USER" VARCHAR2(32 BYTE) DEFAULT USER NOT NULL ENABLE,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "UPDATE_USER" VARCHAR2(32 BYTE) DEFAULT USER NOT NULL ENABLE,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     CONSTRAINT "STUDENT_RECORD_NOTE_PK" PRIMARY KEY ("STUDENT_RECORD_NOTE_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
             STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "API_GRAD_DATA"  ENABLE,
     CONSTRAINT "GRADUTION_STUDENT_RECORD_SRN_FK" FOREIGN KEY ("GRADUTION_STUDENT_RECORD_ID")
         REFERENCES "GRADUATION_STUDENT_RECORD" ("GRADUATION_STUDENT_RECORD_ID") ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;

