CREATE INDEX IDX_GRAD_STUD_REC_SCH_REC
    ON GRADUATION_STUDENT_RECORD (SCHOOL_OF_RECORD_ID)
    TABLESPACE API_GRAD_IDX;

CREATE INDEX IDX_GRAD_STUD_REC_STATUS
    ON GRADUATION_STUDENT_RECORD (STUDENT_STATUS_CODE)
    TABLESPACE API_GRAD_IDX;