ALTER TABLE STUDENT_COURSE
    ADD CONSTRAINT FK_STUDENT_COURSE_GRAD
        FOREIGN KEY (GRADUATION_STUDENT_RECORD_ID)
            REFERENCES GRADUATION_STUDENT_RECORD (GRADUATION_STUDENT_RECORD_ID)
            ENABLE;

