CREATE TABLE "EDW_GRADUATION_SNAPSHOT"
(	 "GRAD_YEAR" NUMBER NOT NULL ENABLE,
     "STUD_NO" VARCHAR2(10 BYTE) NOT NULL ENABLE,
     "GRAD_FLAG" VARCHAR2(1 BYTE),
     "HONOUR_FLAG" VARCHAR2(1 BYTE),
     "STUD_GPA" NUMBER,
     "GRAD_DATE" DATE,
     "NOT_GRAD_REASON_1" VARCHAR2(1 BYTE),
     "NOT_GRAD_REASON_2" VARCHAR2(1 BYTE),
     "NOT_GRAD_REASON_3" VARCHAR2(1 BYTE),
     "NOT_GRAD_REASON_4" VARCHAR2(1 BYTE),
     "NOT_GRAD_REASON_5" VARCHAR2(1 BYTE),
     "NOT_GRAD_REASON_6" VARCHAR2(1 BYTE),
     "NOT_GRAD_REASON_7" VARCHAR2(1 BYTE),
     "NOT_GRAD_REASON_8" VARCHAR2(1 BYTE),
     "NOT_GRAD_REASON_9" VARCHAR2(1 BYTE),
     "NOT_GRAD_REASON_10" VARCHAR2(1 BYTE),
     "NOT_GRAD_REASON_11" VARCHAR2(1 BYTE),
     "NOT_GRAD_REASON_12" VARCHAR2(1 BYTE),
     "RUN_DATE" DATE DEFAULT SYSTIMESTAMP,
     "SESSION_DATE" DATE DEFAULT SYSTIMESTAMP,
     "PRINT_FRENCH_DOG" VARCHAR2(1 BYTE),
     "PRINT_FRANCOPHONE" VARCHAR2(1 BYTE),
     CONSTRAINT "EDW_GRADUATION_STATUS_PK" PRIMARY KEY ("GRAD_YEAR", "STUD_NO")
         USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE
) SEGMENT CREATION IMMEDIATE
    TABLESPACE "API_GRAD_DATA"   NO INMEMORY;
