UPDATE  HISTORY_ACTIVITY_CODE SET EFFECTIVE_DATE =TIMESTAMP'2024-05-15 00:00:00.0' WHERE HISTORY_ACTIVITY_CODE IN ('USERCOURSEADD','USERCOURSEMOD','USERCOURSEDEL')

INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) VALUES ('USEREXAMADD','User Add Student Course/Exam','Student course/exam record added by User',330,TIMESTAMP'2024-05-15 00:00:00.0',NULL);

INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) VALUES ('USEREXAMMOD','User Modify Student Course/Exam','Student course /exam record modified by User',340,TIMESTAMP'2024-05-15 00:00:00.0',NULL);

INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) VALUES ('USEREXAMDEL','User Deleted Student Course/Exam','Student course/exam record deleted by User',350,TIMESTAMP'2024-05-15 00:00:00.0',NULL);
