-- API_GRAD_STUDENT.HISTORY_ACTIVITY_CODE definition

CREATE TABLE "HISTORY_ACTIVITY_CODE" 
   (	"HISTORY_ACTIVITY_CODE" VARCHAR2(15) NOT NULL ENABLE, 
	"LABEL" VARCHAR2(30) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255) NOT NULL ENABLE, 
	"DISPLAY_ORDER" NUMBER NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE, 
	"CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"CREATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE, 
	"UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE, 
	 CONSTRAINT "HISTORY_ACTIVITY_CODE_PK" PRIMARY KEY ("HISTORY_ACTIVITY_CODE")
  USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;
