INSERT INTO HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE)
VALUES ('TVRDELETED','Delete Student TVR','TVR deleted by User Request (Delete Student Reports)',270,TIMESTAMP'2024-06-24 00:00:00.0',NULL);
