
CREATE TABLE "STATUS_EVENT"
(	"EVENT_ID" RAW(16),
     "EVENT_PAYLOAD" BLOB,
     "EVENT_STATUS" VARCHAR2(50 BYTE),
     "EVENT_TYPE" VARCHAR2(100 BYTE),
     "SAGA_ID" RAW(16),
     "EVENT_OUTCOME" VARCHAR2(100 BYTE),
     "REPLY_CHANNEL" VARCHAR2(100 BYTE),
     "CREATE_USER" VARCHAR2(32 BYTE),
     "CREATE_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
     "UPDATE_USER" VARCHAR2(32 BYTE),
     "UPDATE_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA" NO INMEMORY ;