INSERT INTO HISTORY_ACTIVITY_CODE
(HISTORY_ACTIVITY_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE)
VALUES
    ('TVRDELETE','TVR Delete','TVR Report deleted for a Student',300,
     TIMESTAMP'2024-06-21 00:00:00.0',NULL);


