#Keycloak/OAuth properties
security:
  oauth2:
    resource:
      jwt:
        key-value: ${KEYCLOAK_PUBLIC_KEY}

#DB Properties
spring:
  jmx:
    enabled: false
  datasource:
    hikari:
      pool-name: gradstudent-api-cp
      maximum-pool-size: ${MAXIMUM_POOL_SIZE}
      connection-timeout: ${CONNECTION_TIMEOUT}
      max-lifetime: ${MAX_LIFETIME}
    url: ${JDBC_URL}
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
    driver-class: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
  mvc:
    log-request-details: ${SPRING_SHOW_REQUEST_DETAILS}
  jackson:
    deserialization:
      fail-on-unknown-properties: false

#Logging properties
logging:
  file:
    max-history: 1
    clean-history-on-start: true
    max-size: 20MB
    name: /logs/app.log
  #pattern:
  #  file: %d | [${HOSTNAME}] | %clr(%5p) | [%t]   | %logger{36}:%L | %msg%n
  #  console: %d | [${HOSTNAME}] | %clr(%5p) | [%t]   | %logger{36}:%L | %msg%n
  level:
    ca:
      bc:
        gov:
          educ:
            api:
              gradstudent: ${APP_LOG_LEVEL}
    org:
      springframework:
        web: ${SPRING_WEB_LOG_LEVEL}
        security: ${SPRING_SECURITY_LOG_LEVEL}
        boot:
          autoconfigure:
            logging: ${SPRING_BOOT_AUTOCONFIG_LOG_LEVEL}

#Local properties
server:
  undertow:
    threads:
      worker: 128
      io: 16
  #port: ${HTTP_PORT}
  tomcat:
    connection-timeout: 200s

#Endpoint properties
endpoint:
  graduation-status-api:
    read-grad-status:
      url: https://educ-grad-graduation-status-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/gradstatus/studentid/%s
  pen-student-api:
    search:
      url: https://student-api-75e61b-tools.apps.silver.devops.gov.bc.ca/api/v1/student/paginated?pageNumber=%s&pageSize=%s&searchCriteriaList=%s
    by-pen:
      url: https://student-api-75e61b-tools.apps.silver.devops.gov.bc.ca/api/v1/student?pen=%s
  grad-student-api:
    get-student-by-pen:
      url: https://gradstudent-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1
    get-all-students:
      url: https://gradstudent-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/gradstudent
  student-course-api:
    get-student-course-by-pen:
      url: https://student-course-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/studentcourse/pen
  student-assessment-api:
    get-student-assessment-by-pen:
      url: https://student-assessment-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1
  school-api:
    school-by-min-code:
      url: https://educ-grad-school-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/school/%s
  code-api:
    country:
      country-by-country-code:
        url: https://educ-grad-code-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/code/country/%s
      all-countries:
        url: https://educ-grad-code-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/code/country
    province:
      province-by-prov-code:
        url: https://educ-grad-code-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/code/province/%s
      all-provinces:
        url: https://educ-grad-code-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/code/province
