#Keycloak/OAuth properties
security:
  oauth2:
    resource:
      jwt:
        key-value: ${KEYCLOAK_PUBLIC_KEY}

#DB Properties
spring:
  jmx:
    enabled: false
  datasource:
    hikari:
      pool-name: educ-grad-student-api-cp
      maximum-pool-size: ${MAXIMUM_POOL_SIZE}
      connection-timeout: ${CONNECTION_TIMEOUT}
      max-lifetime: ${MAX_LIFETIME}
    url: ${CONNECTION_STRING}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
  mvc:
    log-request-details: ${SPRING_SHOW_REQUEST_DETAILS}
  jackson:
    deserialization:
      fail-on-unknown-properties: false

#Logging properties
logging:
  file:
    max-history: 1
    clean-history-on-start: true
    max-size: 20MB
    name: /logs/app.log
  #pattern:
  #  file: %d | [${HOSTNAME}] | %clr(%5p) | [%t]   | %logger{36}:%L | %msg%n
  #  console: %d | [${HOSTNAME}] | %clr(%5p) | [%t]   | %logger{36}:%L | %msg%n
  level:
    ca:
      bc:
        gov:
          educ:
            api:
              gradstudent: ${APP_LOG_LEVEL}
    org:
      springframework:
        web: ${SPRING_WEB_LOG_LEVEL}
        security: ${SPRING_SECURITY_LOG_LEVEL}
        boot:
          autoconfigure:
            logging: ${SPRING_BOOT_AUTOCONFIG_LOG_LEVEL}

#Local properties
server:
  undertow:
    threads:
      worker: 128
      io: 16
  #port: ${HTTP_PORT}
  tomcat:
    connection-timeout: 200s

#API Documentation
springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/api-docs-ui.html
    operationsSorter: alpha

#Endpoint properties
endpoint:
  grad-trax-api:
    school-by-min-code:
      url: ${GRAD_TRAX_API}api/v1/school/%s
  grad-program-api:
    optional_program_name_by_optional_program_id:
      url: ${GRAD_PROGRAM_API}api/v1/program/optionalprograms/id/%s
    special_program_id_by_program_code_special_program_code:
      url: ${GRAD_PROGRAM_API}api/v1/programmanagement/optionalprograms/%s/%s
    program_name_by_program_code:
      url: ${GRAD_PROGRAM_API}api/v1/program/programs/%s
    career_program-by-career-code: 
      url: ${GRAD_PROGRAM_API}api/v1/program/careerprogram/%s
  grad-student-graduation-api:
    ungrad-reason: 
      ungrad-reason-by-reason-code: 
        url: ${GRAD_STUDENT_GRADUATION_API}api/v1/ungrad/ungradreason/%s
    save-student-ungrad-reason:
      url: ${GRAD_STUDENT_GRADUATION_API}api/v1/ungrad/studentungradreason/studentid/%s
  pen-student-api:
    by-studentid:
      url: ${PEN_API}api/v1/student/%s
    search:
      url: ${PEN_API}api/v1/student/paginated
    by-pen:
      url: ${PEN_API}api/v1/student?pen=%s
  grad-graduation-report-api:
    delete-student-achievement:
      url: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/studentachievement/%s
