package ca.bc.gov.educ.api.gradstudent.util;

public class PermissionsConstants {
	private PermissionsConstants() {}

	public static final String PREFIX = "#oauth2.hasAnyScope('";
	public static final String SUFFIX = "')";

	public static final String UPDATE_GRADUATION_STUDENT = PREFIX + "UPDATE_GRAD_GRADUATION_STATUS" + SUFFIX;
	public static final String READ_GRADUATION_STUDENT = PREFIX + "READ_GRAD_GRADUATION_STATUS" + SUFFIX;
	public static final String UPDATE_GRADUATION_STUDENT_OPTIONAL_PROGRAM = PREFIX + "UPDATE_GRAD_STUDENT_SPECIAL_DATA" + SUFFIX;
	public static final String READ_GRADUATION_STUDENT_OPTIONAL_PROGRAM = PREFIX + "READ_GRAD_STUDENT_SPECIAL_DATA" + SUFFIX;

	public static final String READ_GRAD_STUDENT_CAREER_DATA = PREFIX + "READ_GRAD_STUDENT_CAREER_DATA" + SUFFIX;
	public static final String READ_GRAD_STUDENT_UNGRAD_REASONS_DATA = PREFIX + "READ_GRAD_STUDENT_UNGRAD_REASONS_DATA" + SUFFIX;
	public static final String CREATE_GRAD_STUDENT_UNGRAD_REASONS_DATA = PREFIX + "CREATE_GRAD_STUDENT_UNGRAD_REASONS_DATA" + SUFFIX;
	public static final String UPDATE_GRADUATION_STUDENT_REPORTS = PREFIX + "UPDATE_GRAD_STUDENT_REPORT_DATA" + SUFFIX;
	public static final String READ_GRADUATION_STUDENT_REPORTS = PREFIX + "READ_GRAD_STUDENT_REPORT_DATA" + SUFFIX;
	public static final String READ_GRADUATION_STUDENT_CERTIFICATES = PREFIX + "READ_GRAD_STUDENT_CERTIFICATE_DATA" + SUFFIX;
	public static final String UPDATE_GRADUATION_STUDENT_CERTIFICATES = PREFIX + "UPDATE_GRAD_STUDENT_CERTIFICATE_DATA" + SUFFIX;
	public static final String READ_GRAD_ALGORITHM_RULES = PREFIX + "READ_GRAD_ALGORITHM_RULES_DATA" + SUFFIX;
	public static final String READ_GRAD_STUDENT_NOTES_DATA = PREFIX + "READ_GRAD_STUDENT_NOTES_DATA" + SUFFIX;
	public static final String CREATE_OR_UPDATE_GRAD_STUDENT_NOTES_DATA = PREFIX + "CREATE_GRAD_STUDENT_NOTES_DATA', 'UPDATE_GRAD_STUDENT_NOTES_DATA" + SUFFIX;
	public static final String DELETE_GRAD_STUDENT_NOTES_DATA = PREFIX + "DELETE_GRAD_STUDENT_NOTES_DATA" + SUFFIX;

	public static final String CREATE_STUDENT_STATUS = PREFIX + "CREATE_GRAD_STUDENT_STATUS_CODE_DATA"+ SUFFIX;
	public static final String READ_GRAD_STUDENT_STATUS = PREFIX + "READ_GRAD_STUDENT_STATUS_CODE_DATA" + SUFFIX;
	public static final String READ_GRAD_HISTORY_ACTIVITY = PREFIX + "READ_GRAD_HISTORY_ACTIVITY_CODE_DATA" + SUFFIX;
	public static final String DELETE_STUDENT_STATUS = PREFIX + "DELETE_GRAD_STUDENT_STATUS_CODE_DATA"+ SUFFIX;
	public static final String UPDATE_STUDENT_STATUS = PREFIX + "UPDATE_GRAD_STUDENT_STATUS_CODE_DATA"+ SUFFIX;
	public static final String STUDENT_ALGORITHM_DATA = PREFIX + "READ_GRAD_GRADUATION_STATUS', 'READ_GRAD_STUDENT_DATA" + SUFFIX;
}
